---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./certificates/ks.yaml
  - ./gateway-api-crds/ks.yaml
  - ./gateway/ks.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./csi-driver-nfs/ks.yaml
  - ./descheduler/ks.yaml
  # - ./nvidia-device-plugin/ks.yaml  # Removed - no NVIDIA hardware in cluster

  - ./metrics-server/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./smarter-device-manager/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./spegel/ks.yaml
  - ./reloader/ks.yaml
  - ./talos-backup/ks.yaml
