---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./externalsecret.yaml
  - ./configmap.yaml
components:
  - ../../../../components/volsync
  - ../../../../components/externalsecret-refresh

