---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./audiobookshelf/ks.yaml
  - ./bazarr/ks.yaml
  - ./calibre-web/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./immich/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./lidarr/ks.yaml
  - ./notifiarr/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr-audiobooks/ks.yaml
  - ./readarr-ebooks/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./tdarr/ks.yaml
