---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/externalsecret-refresh
  # NOTE: VolSync intentionally NOT included
  # - All config is declarative in HelmRelease
  # - PostgreSQL backed up via Barman
  # - All repos are proxies (cache only, re-fetchable)

resources:
  - ./externalsecret.yaml
  # PVC managed by StatefulSet volumeClaimTemplate (longhorn-1-replica)
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./servicemonitor.yaml
