---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nexus
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nexus3
      app.kubernetes.io/instance: nexus
  endpoints:
    - port: http
      path: /service/rest/metrics/prometheus
      interval: 30s
      # Nexus metrics require authentication (admin user)
      basicAuth:
        username:
          name: nexus-secret
          key: NEXUS_ADMIN_USERNAME
        password:
          name: nexus-secret
          key: NEXUS_SECURITY_INITIAL_PASSWORD
