---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app drone
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: gitea
      namespace: develop
    - name: cloudnative-pg-cluster
      namespace: database
    - name: external-secrets-stores
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/develop/drone/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  targetNamespace: develop
  wait: false
  postBuild:
    substitute:
      APP: *app
      NS: develop
      GATUS_PORT: "80"
      GATUS_SERVICE: drone
      GATUS_SUBDOMAIN: drone

