---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name joplin-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore

  target:
    name: *name
    template:
      engineVersion: v2
      data:
        POSTGRES_CONNECTION_STRING: postgresql://{{ .Joplin__PostgresUser }}:{{ .Joplin__PostgresPass }}@postgres16-rw.database.svc.cluster.local:5432/{{ .Joplin__DbName }}
        # Postgres Init
        INIT_POSTGRES_DBNAME: "{{ .Joplin__DbName }}"
        INIT_POSTGRES_HOST: &pghost postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .Joplin__PostgresUser }}"
        INIT_POSTGRES_PASS: "{{ .Joplin__PostgresPass }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .Postgres__SuperPassword }}"
  dataFrom:
  - extract:
      key: cloudnative-pg
  - extract:
      key: joplin
