---
# Service for Garage web UI - routes to external IP
apiVersion: v1
kind: Service
metadata:
  name: openspeedtest
spec:
  ports:
    - name: http
      port: 80
      targetPort: 30116
      protocol: TCP
---
# EndpointSlice for openspeedtest web UI
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: openspeedtest-1
  labels:
    kubernetes.io/service-name: openspeedtest
addressType: IPv4
ports:
  - name: http
    port: 30116
    protocol: TCP
endpoints:
  - addresses:
      - "10.0.10.10"

