---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name authentik-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore

  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # PostgreSQL init container
        INIT_POSTGRES_SUPER_PASS: "{{ .Postgres__SuperPassword }}"
        INIT_POSTGRES_DBNAME: "{{ .Authentik__PostgresDbname }}"
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .Authentik__PostgresUser }}"
        INIT_POSTGRES_PASS: "{{ .Authentik__PostgresPass }}"
        # Authentik configuration
        AUTHENTIK_SECRET_KEY: "{{ .Authentik__SecretKey }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .Authentik__BootstrapPassword }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .Authentik__BootstrapToken }}"
        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .Authentik__BootstrapEmail }}"
        # PostgreSQL connection
        AUTHENTIK_POSTGRESQL__HOST: postgres16-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: "{{ .Authentik__PostgresDbname }}"
        AUTHENTIK_POSTGRESQL__USER: "{{ .Authentik__PostgresUser }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .Authentik__PostgresPass }}"
        # Redis connection
        AUTHENTIK_REDIS__HOST: dragonfly.database.svc.cluster.local

  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: authentik

