---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: graphite-exporter
spec:
  interval: 12h
  url: oci://ghcr.io/bjw-s/helm
  ref:
    semver: ">=4.0.0"

