---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./httproute.yaml
  # - ./pushsecret.yaml
components:
  - ../../../../components/externalsecret-refresh
configMapGenerator:
  - name: thanos-cache-configmap
    files:
      - cache.yaml=./resources/cache.yaml
generatorOptions:
  disableNameSuffixHash: true
