---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/externalsecret-refresh
  - ../../../../components/gatus-guarded

resources:
  - ./configmap.yaml
  - ./externalsecret.yaml
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./rbac.yaml

