---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - ./statefulset.yaml
  - ./service.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: dev-ubuntu
      app.kubernetes.io/part-of: dev-ubuntu
