---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ocirepository.yaml
  - pvc.yaml
  - helmrelease.yaml
  - dnsendpoint.yaml
  - externalsecret.yaml
  - ../../../../templates/volsync
