---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/volsync
  - ../../../../components/volsync-syncthing

resources:
  - ocirepository.yaml
  - pvc.yaml
  - helmrelease.yaml
  - dnsendpoint.yaml
  - externalsecret.yaml
