---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./dnsendpoint.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./helmrelease-quic.yaml
configMapGenerator:
  - name: cloudflare-tunnel-configmap
    files:
      - ./configs/config.yaml
generatorOptions:
  disableNameSuffixHash: true
