---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mosquitto
  namespace: infrastructure
spec:
  secretName: mosquitto-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  dnsNames:
    - "mqtt.${SECRET_DOMAIN_MEDIA}"
    - "mqtt.${SECRET_DOMAIN}"

