---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gitea
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: database
    - name: external-secrets-stores
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/develop/gitea/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  targetNamespace: develop
  wait: false
  postBuild:
    substitute:
      APP: *app
      NS: develop
      GATUS_PORT: "3000"
      GATUS_SERVICE: gitea-http
      GATUS_SUBDOMAIN: gitea
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_STORAGECLASS: truenas-nfs
      VOLSYNC_SNAPSHOTCLASS: truenas-nfs-snapclass
      VOLSYNC_CACHE_CLASS: truenas-nfs
      VOLSYNC_CLONE_STORAGECLASS: truenas-nfs
      VOLSYNC_LOCAL_SCHEDULE: "*/30 * * * *"

