---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name nextcloud-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore

  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # Postgres Init container variables
        INIT_POSTGRES_DBNAME: "{{ .Nextcloud__DbName }}"
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .Nextcloud__PostgresUser }}"
        INIT_POSTGRES_PASS: "{{ .Nextcloud__PostgresPass }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .Postgres__SuperPassword }}"
        # Nextcloud database configuration
        POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        POSTGRES_DB: "{{ .Nextcloud__DbName }}"
        POSTGRES_USER: "{{ .Nextcloud__PostgresUser }}"
        POSTGRES_PASSWORD: "{{ .Nextcloud__PostgresPass }}"
        # Nextcloud admin credentials
        NEXTCLOUD_ADMIN_USER: "{{ .Nextcloud__AdminUser }}"
        NEXTCLOUD_ADMIN_PASSWORD: "{{ .Nextcloud__AdminPassword }}"
        # OAuth credentials for Authentik integration
        OIDC_CLIENT_ID: "{{ .Nextcloud__OAuthClientId }}"
        OIDC_CLIENT_SECRET: "{{ .Nextcloud__OAuthClientSecret }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: nextcloud

