---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name gitea-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # PostgreSQL connection for Gitea
        GITEA__database__USER: "{{ .Gitea__Postgres__User }}"
        GITEA__database__PASSWD: "{{ .Gitea__Postgres__Password }}"
        # Secret key for signing
        GITEA__security__SECRET_KEY: "{{ .Gitea__SecretKey }}"
        GITEA__security__INTERNAL_TOKEN: "{{ .Gitea__InternalToken }}"
        # LFS JWT secret
        GITEA__server__LFS_JWT_SECRET: "{{ .Gitea__LfsJwtSecret }}"
        # OAuth2 JWT secret
        GITEA__oauth2__JWT_SECRET: "{{ .Gitea__Oauth2JwtSecret }}"
        # Postgres Init container variables
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .Gitea__Postgres__User }}"
        INIT_POSTGRES_PASS: "{{ .Gitea__Postgres__Password }}"
        INIT_POSTGRES_DBNAME: gitea
        INIT_POSTGRES_SUPER_PASS: "{{ .Postgres__SuperPassword }}"
  dataFrom:
    - extract:
        key: gitea
    - extract:
        key: cloudnative-pg

