---
# This GitRepository is created for flux-local testing purposes only
# In the actual cluster, this is created by the Flux instance HelmRelease
# See: kubernetes/apps/flux-system/flux-instance/app/helmrelease.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-kubernetes
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/bluevulpine/flux-talos.git
  ref:
    branch: main
