---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: mqtt
spec:
  endpoints:
    - dnsName: "mqtt.${SECRET_DOMAIN_MEDIA}"
      recordType: CNAME
      targets: ["wheels.${SECRET_DOMAIN_MEDIA}"]
      providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "false"
    - dnsName: "mqtt.${SECRET_DOMAIN}"
      recordType: CNAME
      targets: ["wheels.${SECRET_DOMAIN_MEDIA}"]
      providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "false"
