---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name drone-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # Gitea OAuth credentials
        DRONE_GITEA_CLIENT_ID: "{{ .Drone__Gitea__ClientId }}"
        DRONE_GITEA_CLIENT_SECRET: "{{ .Drone__Gitea__ClientSecret }}"
        # RPC secret for runner communication
        DRONE_RPC_SECRET: "{{ .Drone__RpcSecret }}"
        # PostgreSQL connection string
        DRONE_DATABASE_DATASOURCE: "postgres://{{ .Drone__Postgres__User }}:{{ .Drone__Postgres__Password }}@postgres16-rw.database.svc.cluster.local:5432/drone?sslmode=disable"
        # Postgres Init container variables
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .Drone__Postgres__User }}"
        INIT_POSTGRES_PASS: "{{ .Drone__Postgres__Password }}"
        INIT_POSTGRES_DBNAME: drone
        INIT_POSTGRES_SUPER_PASS: "{{ .Postgres__SuperPassword }}"
  dataFrom:
    - extract:
        key: drone
    - extract:
        key: cloudnative-pg

