---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drone-runner
  namespace: develop
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "create", "delete", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone-runner
  namespace: develop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drone-runner
subjects:
  - kind: ServiceAccount
    name: drone-runner
    namespace: develop

