---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: productivity
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./atuin/ks.yaml
  - ./grocy/ks.yaml
  - ./homebox/ks.yaml
  - ./homebox-companion/ks.yaml
  - ./joplin-server/ks.yaml
  - ./karakeep/ks.yaml
  - ./mealie/ks.yaml
  - ./nextcloud/ks.yaml
  - ./obsidian/ks.yaml

