---
apiVersion: v1
kind: Namespace
metadata:
  name: develop
  labels:
    name: develop
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
