---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name readarr-audiobooks-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        READARR__AUTH__APIKEY: "{{ .ReadarrAudiobooks__ApiKey }}"
        READARR__POSTGRES__HOST: &dbHost postgres16-rw.database.svc.cluster.local
        READARR__POSTGRES__PORT: "5432"
        READARR__POSTGRES__USER: &dbUser "{{ .ReadarrAudiobooks__Postgres__User }}"
        READARR__POSTGRES__PASSWORD: &dbPass "{{ .ReadarrAudiobooks__Postgres__Password }}"
        READARR__POSTGRES__MAINDB: &dbMain readarr_audiobooks_main
        READARR__POSTGRES__LOGDB: readarr_audiobooks_log
        READARR__POSTGRES__CACHEDB: readarr_audiobooks_cache
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_DBNAME: *dbMain
        INIT_POSTGRES_SUPER_PASS: "{{ .Postgres__SuperPassword }}"
  dataFrom:
    - extract:
        key: readarr-audiobooks
    - extract:
        key: cloudnative-pg

