---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homebox-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore

  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # Postgres Init container variables
        INIT_POSTGRES_DBNAME: "{{ .Homebox__DbName }}"
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .Homebox__PostgresUser }}"
        INIT_POSTGRES_PASS: "{{ .Homebox__PostgresPass }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .Postgres__SuperPassword }}"
        # Database configuration for Homebox
        HBOX_DATABASE_HOST: postgres16-rw.database.svc.cluster.local
        HBOX_DATABASE_PORT: "5432"
        HBOX_DATABASE_USERNAME: "{{ .Homebox__PostgresUser }}"
        HBOX_DATABASE_PASSWORD: "{{ .Homebox__PostgresPass }}"
        HBOX_DATABASE_DATABASE: "{{ .Homebox__DbName }}"
        # OIDC credentials for Authentik integration
        HBOX_OIDC_CLIENT_ID: "{{ .Homebox__OAuthClientId }}"
        HBOX_OIDC_CLIENT_SECRET: "{{ .Homebox__OAuthClientSecret }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: homebox

