---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vaultwarden
  annotations:
    gatus.home-operations.com/endpoint: |
      group: identity
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Vaultwarden"
    gethomepage.dev/group: "Identity"
    gethomepage.dev/icon: "vaultwarden.png"
    gethomepage.dev/description: "Password Manager"
spec:
  hostnames: ["vaultwarden.${SECRET_DOMAIN}"]
  parentRefs:
    # Internal gateway only - not exposed externally
    - name: internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: vaultwarden
          port: 8080

