apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:Is5Amwa5ppuKYx2mtBIvfpHBavouQ1qVSa6rMxfotnXBYt9fsXW4b/ghT3Sbo47tiBrHeEQp+x8WqNUb5FWZVj5yBlQRSMrH017SBNWa6mNZtcmH8Xlxh8ElSKihzriN9QU+9KWnYQs/l3wJDQXO5QjKTROQa4jUiKflEu13wr3yJO9xrq4=,iv:FB/1ZWX/Fg6qlYdUUITjDEyzGFcqun/5vGmObCRbguc=,tag:h8dOcZn6YdO3el5zLc+6Yw==,type:str]
sops:
  age:
    - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWFBndzJqUjZHQmlDSlVJ
        SlFMVUNZNzhubVpjemxDQ2VTSDQ2ZFF6NVY4CklMTG1QRU8rNWlhbU1YeU42QXo5
        a3RNNEJXeTUwTHRuS3ZDWFA4NWxrdkkKLS0tIDdyN1RmeGV2Z2N6a1dBdWNLVHdV
        amxSM0I3c3BqWE1WcGFjdVIxajNBOFkKNmrb5ENRJSOVG+96CTjZTnYu8159VqbN
        VTp809SBF/fqa4Bv/bf66YFoX+zHTgl1Rj4SKf9VfgRCNqpXIZH7uw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T19:39:56Z"
  mac: ENC[AES256_GCM,data:/pg1VhI2yuZmrhw3Z74/Y+HodSAbkG6AJbsAWbqgwtzUDOZS+PLT/aTmd5xXqDSMQNZLCoO2GFBrQh9xJPETUvzGjWy6q2zbqMX0zS7AoZceL1M5aaiWjdmUF6eCs+k2HicCT5Wkvxaj0i79q8jQXGXdiu4KE1ciARxw3hQXPYo=,iv:aZr7KCJ8Xy56/CUfJ199vpB4ONmlt9RAcGydSY4uEF0=,tag:uHlOTxqrE4ho9xf1jkL8LA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
