---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  TIMEZONE: "America/Chicago"
  SVC_K8S_API_ADDR: 172.16.8.1
  SVC_NGINX_INTERNAL: 172.16.8.2
  SVC_NGINX_EXTERNAL: 172.16.8.3
  SVC_POSTGRES_ADDR: 172.16.8.4
  SVC_SMTP_RELAY_ADDR: 172.16.8.5
  SVC_VECTOR_ADDR: 172.16.8.6
  SVC_SATISFACTORY_ADDR: 172.16.8.7
  SVC_MOSQUITTO_ADDR: 172.16.8.8
  SVC_PLEX_ADDR: 172.16.8.9
  SVC_XHA_ADDR: 172.16.8.10
  SVC_SYNCTHING_ADDR: 172.16.8.11
  SVC_VALHEIM_ADDR: 172.16.8.12
  SVC_UDPTEST_ADDR: 172.16.8.13
  SVC_JELLYFIN_ADDR: 172.16.8.14
  SVC_QBITTORRENT_ADDR: 172.16.8.15
  SVC_GITEA_SSH_ADDR: 172.16.8.16
