apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    #ENC[AES256_GCM,data:gqJzi8QlPhlNDKZ9KgmuV9Sy+PybrsGgu47j0Y5DZnPOuu1jyNBexcXSXjfphrnuxa4wZ9Te87tWKAGmi+V5i0lvF3g=,iv:17nrnSVex0haWOfKAJGeWbzksHhqhPlrRUTAOGIv71Y=,tag:Sz5QA3brf7yCtZRpGeceCA==,type:comment]
    DEMOCRATIC_CSI_API_KEY: ENC[AES256_GCM,data:IPJJgejEiApEq7b8odnmbvy6VKXcU2ADlN/IqjZYG+wFQk4FdnjzzrvrHJkdG+hZGGPg9QanIXGgIaDMOdxKM+2h,iv:d1KD2GO25ciAHkuzRB5XZ3qXQcrZ0Gf5gZkKlS04/jM=,tag:wtyGezjzMuRC4WeyLsSHbg==,type:str]
    SECRET_EXAMPLE: ENC[AES256_GCM,data:q1mG+/elv7wRSFH77flk0iyZ4FqcGtOI8aEM6l5kn23aJ67g6i+PiU0UWZOtvjseysqz4ny0CEP9jZT8ng+o7LlNztzaMzhX5ysZJFUhpadD8NQkDVt1Ac8RXnbqvw==,iv:kwy6ZS6s3ySvoQe51TZP/zwO5M9mIjhlnkMHc9xZkWQ=,tag:Y7j1uW4GrcSVlz+zzu0ENQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:FVSydWuwJNAf4YeRGFzFYcMzq5AO7KRrGgQ=,iv:2+9DluC/AuD4c9ftAG4FfTd3Zve/CzjMa7RTWjKdhr8=,tag:x4WBlr1bQe4qCOFGMr9GWw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:BzdMdTzFbsx3pCbYzFsmkIE+8X3mjsW6ipQUL5bZBtlhwWRY,iv:ux8fp/Hwf/JbXqiL5huc7gi7YUtPSGxwZzc95XCF2dk=,tag:CJqR8CZti7lKc4h/1cQyCA==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:l03LFAtXLb3+ZnqQ6B9sq5hXL/Qg+MgoeviLM2nZDcI=,iv:oVxr3uYHxH1uSB/9KWiivn6BuXnGbtFbWVROdA8fhI0=,tag:3YU0WFx6KoRWCqUNfnul7A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:419KwHQXAfgm/inEPMJy,iv:z33f4K7UHuNpMVdqcESEYnmETUSLFF0DYvC4D5H6QCQ=,tag:61gX0iKtIibzBvy6l3QMNw==,type:str]
    SECRET_DOMAIN_BLOG: ENC[AES256_GCM,data:XzCjIgOPlLu4y7CRTfW6,iv:f8Q3bRE+UxQgKvv3gcxmeuC6f2OpmwaVNHLIF5b3y8M=,tag:X0jEpDbjdEmsyo54g3pbdg==,type:str]
    SECRET_DOMAIN_BLOGCOM: ENC[AES256_GCM,data:vfnaJ7g62wTSHeww/sdd,iv:JC0v9zhH4vaQs/pwv31IYuvs9JAuTjFFvWSWj+OutaM=,tag:5ydPO4KTXkxYyXSlIXfr7w==,type:str]
    SECRET_DOMAIN_MEDIA: ENC[AES256_GCM,data:83/pYZuSQg==,iv:MJDaOPPRfS4zGQBIlXIq4x7MRzfRYfEKCDKQNOqpxxU=,tag:OEg9xhTlncm3W7kb0tYmmw==,type:str]
    SECRET_DOMAIN_LAKE: ENC[AES256_GCM,data:YA3ebOpfHzeNEF7z,iv:lh1uS97/Jgh85DPiwiJKXgPpYNfr6TMOm4GAo3s/7cc=,tag:WgkMwiisGMpClKMdpe2RZA==,type:str]
    SECRET_DOMAIN_YOYO: ENC[AES256_GCM,data:NkmOAQLEy0mlY62287/zkA==,iv:S0JwSgoVIKb+oV/iapMx7lohJfKp+wZLij4+JTgCJLg=,tag:xyKloE0nrw2l7YoBfTW0tQ==,type:str]
    SECRET_DOMAIN_BON: ENC[AES256_GCM,data:4eZuztRXvUnekLc5o6Fn,iv:2u28ffTZf90Kf5wKGhQ3D73g2BtgW94gKJAQZ8AbucY=,tag:r5L7f3iqokYxOOxQqD4/Sg==,type:str]
    #ENC[AES256_GCM,data:jqR9IyEIAQlDE2MblkTCCdWUIOGeZATCvwUw6yRt77IHCj+8KAKNNblroT2GsKs28jhi5169NMlRZDAAgH3JwgplyQUBO9qnVeTfM4mHxSRuffUy19WbMs/psp5eMUfcT9joO6X2PQ==,iv:Oj9nNTLHIcIZ3M67Udxy0+KIHQfIJtOhXB3KgA7+Dpo=,tag:wplG5wYC9bCO2GCP8ONPzw==,type:comment]
    SECRET_GARAGE_S3_ENDPOINT: ENC[AES256_GCM,data:iDwGqTEY+BGXKqQqlCSH3fpURFUDLApD6mY=,iv:K7Idyp2za7LeHndSEgugem/B8VNLxYVbtaOlRceiNsk=,tag:R1gTqjGaKnl5DAS3dtDFOQ==,type:str]
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:2L9yUGtakcbwN0wdgw==,iv:QIQeQHxiqebBzmMjV1JIbrPl+4UX8DiCtXlm+dot2I8=,tag:kVxOY38r0cSE06f7SEhV4Q==,type:str]
    SECRET_NFS_MEDIA: ENC[AES256_GCM,data:S83c53pWU8Hb3DayrTTpvLsh+622+w==,iv:/pAaDAwU6F4fUilg99Vm6dvIBOcF1sStYzNMFveqUio=,tag:n0lNMj+V9NjMf+s3/TQMHA==,type:str]
    SECRET_NFS_MEDIA_HOME: ENC[AES256_GCM,data:YNRAMvW+86lvujB29/oyHPB9als=,iv:yvHcUTCOKd4l/zkEsIxelBCalWHiVEwoI1tJqj5IBTU=,tag:N0bs5xPebJr5WVEmlsJXFw==,type:str]
    SECRET_NFS_KUBERNETES: ENC[AES256_GCM,data:GkgtRHqMCG1S3w5ZKwX5HThZMEg=,iv:VMlOsIEXu08UtL9VS5BeUUztIuZcVRiBPAA7rG91gXE=,tag:h6O66pgLFNfJBmTSWH99Ow==,type:str]
    SECRET_NFS_KOPIA: ENC[AES256_GCM,data:/GRaSI+ZcI7G9AFkCdC6MAM=,iv:W1PtdXcpPUqMTkJGDxQCJ7lpfiE+oB09UJKRGdL5wxY=,tag:RaAs6FibTR+ogvzXnUiFgw==,type:str]
    SECRET_PG_ADMIN: ENC[AES256_GCM,data:JvASyO2bIzxx5V6kdOR/uZKqjGOwO4KkaDhHXrmWljbxbV4i8WQ1JUo5t+SGfTeMFbtYe+ReB3hJ+S9PS4f/6xsGk/nYRmQTWgRCz22s7FuOWJJAtjGR9bxZ05zDwtSRVf3+AWBAR3U9vEYEhMWRCUy4zhJcWpzTAdQdht7mupE=,iv:I7gMbXgBEGcBjgn2hvZIpXWeZ0aW1ncfu4SLMJW9x+g=,tag:PSmnB2h+puBGfQz1py6YSw==,type:str]
    SECRET_TS_ADMIN: ENC[AES256_GCM,data:K/+nOMp0a2a9l0mPM/o0jIiM,iv:ChNJXvGY/ZAu1mNAvTGORPU1s8SutG7re9KQNQXVg3k=,tag:DxW7ymXOSnVM4PQqFel4Sw==,type:str]
    BW_PROJECT_ID: ENC[AES256_GCM,data:ToQ+M/ep/4BRMkMXdtwGI2+mXdm0JGyoyJJXuJOHeaE7jeem,iv:hAE6L6w4ufDsqhICEwVbYPvlJhZpTlbqDNA+SVoWxWA=,tag:fjA3mOpQYqhrjNfXagTiCQ==,type:str]
    BW_ORG_ID: ENC[AES256_GCM,data:3VELCJ0UdXbVHEAk+dGxMQ4AjVVRc3pGDJqY72WwLkx13KNE,iv:oXdvGe/0IH5xx7ZaBzuADSNcgcQ+oGV377oiVnKlGV8=,tag:kFcvNbczJdjJDUVE0u8EDQ==,type:str]
sops:
    age:
        - recipient: age1ww3u7me5lwxtgqcd8djkv485q30wu7k40hs9e2acg8qvdw4e8spq9t5dem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNTJVNWpvL0FDVzVvWXo5
            UUpycDdzeWhkdEt6dGs5MjdVVnN4bWIxazJFCnBpYzlrRkVici8vektVYzFFWEVC
            dUxrWExnUWswVThNQ2tkbVFYUGN6bEEKLS0tIGk0R1JoeHpzVWw4WUNmcUpwb0Z2
            K3ZKSlZmYWVXSjRpMXVKVFhYekl5VG8K/GC8V0X1agsQ3g7mYEOpgJHAphGZnwGi
            j4Nls0ueKKhd6H/cGl44GP/vUg6Bmstc+DQRlPr8w+h5ps8zA5GiXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T20:54:39Z"
    mac: ENC[AES256_GCM,data:fAaPyFTm8O22hYo4XhsJpYHqg+Y3S9UC0GSROMwLJUTodwuVVNRRCkwiKYN6iRS4Ewdg9dff2NtSFE/KQZVCZElU6XEW1522fqXv27F/7ykbHZhGCv60iUZA2TY4p5bUeeQE/vi7cWvw72JzDrp+wUpHiJa+WX4dhWR6/TUCENo=,iv:YmXGf+jbv+UdZV/WyhxY+y8Xp3SmQ1bsDhVROJk7X6Y=,tag:djmMbdayNgnmqFjikyL1rg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
